# Generated by Django 4.2.1 on 2023-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0004_profile_friends_delete_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_requests_received',
            field=models.ManyToManyField(blank=True, related_name='received_friend_requests', to='blog_user.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_requests_sent',
            field=models.ManyToManyField(blank=True, related_name='sent_friend_requests', to='blog_user.profile'),
        ),
    ]
