# Generated by Django 4.2.1 on 2023-06-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0005_profile_friend_requests_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friend_requests_received',
            new_name='requests_received',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='friend_requests_sent',
            new_name='requests_sent',
        ),
    ]
