# Generated by Django 4.2.1 on 2023-06-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0006_rename_friend_requests_received_profile_requests_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='blog_user.profile'),
        ),
    ]
